import Head from "next/head";
import Image from "next/image";
import React from "react";
import Navbar from "../components/Navbar";
import styles from "../styles/pages/depoimentos.module.scss";
import { DepoimentosFake } from "../utils/depoimentos-fake";

export default function depoimentos() {
  return (
    <>
      <Head>
        <title>Cicareli - Depoimentos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#F2F6FA" />
        <link rel="icon" href="/icons/favicon.svg" />
      </Head>
      <Navbar />
      <div className={styles.main}>
        <div className={styles.titulo}>
          <Image
            src={"/icons/tree-left.svg"}
            alt="slskdf"
            width={50}
            height={50}
          />
          <span>Depoimentos</span>
          <Image
            src={"/icons/tree-right.svg"}
            alt="slskdf"
            width={50}
            height={50}
          />
        </div>
        <div className={styles.descricao}>
          <p>Vem saber o que falam de nós!</p>
        </div>
      </div>
      <div className={styles.espacosMain}>
        {DepoimentosFake.map((x, index) => (
          <div className={styles.card}>
            <div className={styles.line}></div>
            <p className={styles.depoimento}>{x.depoimento}</p>
            <p className={styles.autor}>{x.autor}</p>
          </div>
        ))}
      </div>
    </>
  );
}
