import Head from "next/head";
import Image from "next/image";
import React from "react";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import WhatsappIcon from "../components/WhatsappIcon";
import styles from "../styles/pages/gastronomia.module.scss";
import { motion } from "framer-motion"


export default function gastronomia() {
  return (
    <div className="">
      <Head>
        <title>Cicareli - Gastronomia</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#F2F6FA" />
        <link rel="icon" href="/icons/favicon.svg" />
      </Head>
      <Navbar />
      <motion.div initial="pageInitial" animate="pageAnimate" variants={{
        pageInitial: {
          opacity: 0
        }, 
        pageAnimate: {
          opacity: 1
        }
      }}>

        <div className={styles.main}>
          <div className={styles.imagem}>
            <img
              src={"/images/gastronomia.webp"}
              alt="Foto de um cozinheiro finalizando um prato."
              width={600}
              height={700}
            />
          </div>
          <div className={styles.descricao}>
            <div className={styles.titulo}>
              <h1>Gastronomia</h1>
              <img
                style={{ objectFit: "contain", objectPosition: "18% 100%" }}
                src={"/icons/tree-right.svg"}
                alt="Símbolo Cicareli virado para a direita"
                width={30}
                height={30}
                // objectFit
              />
            </div>

            <p>
              Os cardápios do Buffet Cicareli são elaborados de forma
              personalizada, com sofisticação e elegância para atender os momentos
              mais especiais.{" "}
            </p>
            <p>
              A equipe é treinada e especializada, na cozinha unimos formação
              internacional com mais de 70 anos de prática.
            </p>
          </div>
        </div>
      </motion.div>
      <WhatsappIcon />
      <Footer />

    </div>
  );
}
