import Head from "next/head";
import Image from "next/image";
import React from "react";
import Navbar from "../components/Navbar";
import styles from "../styles/pages/gastronomia.module.scss";

export default function gastronomia() {
  return (
    <div className="">
      <Head>
        <title>Cicareli - Gastronomia</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#F2F6FA" />
        <link rel="icon" href="/icons/favicon.svg" />
      </Head>
      <Navbar />
      <div className={styles.main}>
        <div className={styles.imagem}>
          <Image
            src={"/images/gastronomia.webp"}
            alt="Foto de um cozinheiro finalizando um prato."
            width={600}
            height={700}
          />
        </div>
        <div className={styles.descricao}>
          <div className={styles.titulo}>
            <h1>Gastronomia</h1>
            <Image
              src={"/icons/tree-right.svg"}
              alt="Símbolo Cicareli virado para a direita"
              width={30}
              height={30}
            />
          </div>

          <p>
            Os cardápios do Buffet Cicareli são elaborados de forma
            personalizada, com sofisticação e elegância para atender os momentos
            mais especiais.{" "}
          </p>
          <p>
            A equipe é treinada e especializada, na cozinha unimos formação
            internacional com mais de 70 anos de prática.
          </p>
        </div>
      </div>
    </div>
  );
}
