import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Navbar from "../components/Navbar";
import { useRouter } from "next/router";
import WhatsappIcon from "../components/WhatsappIcon";

export default function Home() {
  const { push } = useRouter();

  return (
    <div className={styles.bodyAll}>
      <Head>
        <title>Buffet Cicarelli</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#F2F6FA" />
        <link rel="icon" href="/icons/favicon.svg" />
      </Head>
      <Navbar />
      <div className={styles.bannerHome}>
        <div className={styles.introduction}>
          <p>
            Buffet Cicareli <br /> desde 1970.
          </p>
          <span>Eventos Gourmet, Sociais e Corporativos</span>
          <button onClick={() => push("quem-somos")}>Saber Mais</button>
        </div>
      </div>
      <WhatsappIcon />
    </div>
  );
}
