import Head from "next/head";
import Image from "next/image";
import React from "react";
import Input from "../components/Input";
import Navbar from "../components/Navbar";
import styles from "../styles/pages/orcamento.module.scss";

export default function orcamento() {
  return (
    <div className={styles.main}>
      <Head>
        <title>Buffet Cicarelli</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#F2F6FA" />
        <link rel="icon" href="/icons/favicon.svg" />
      </Head>
      <Navbar />
      <div className={styles.content}>
        <h1>Contato</h1>
      </div>
      <div className={styles.mainContentForm}>
        <div className={styles.introduction}>
          <h2>Peça um orçamento</h2>
          <span>Preencha o formulário ao lado e entraremos em contato!</span>
          <Image
            src={"/images/bolo-orcamento.png"}
            alt="Bolo de chocolate"
            width={488}
            height={649}
          />
        </div>
        <form className={styles.formContato}>
          <Input name="nome" type="text" label="Nome" required />
        </form>
      </div>
    </div>
  );
}
