import { motion } from 'framer-motion';
import Head from 'next/head'
import React from 'react'
import { FooterCompleto } from '../components/FooterCompleto';
import Navbar from '../components/Navbar';
import styles from "../styles/pages/politica.module.scss";


export default function PoliticaPrivacidade() {
  return (
    <div><div className={styles.main}>
    <Head>
      <title>Buffet Cicarelli</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta name="theme-color" content="#F2F6FA" />
      <link rel="icon" href="/icons/favicon.svg" />
    </Head>
    <Navbar />
    <motion.div
      initial="pageInitial"
      animate="pageAnimate"
      variants={{
        pageInitial: {
          opacity: 0,
        },
        pageAnimate: {
          opacity: 1,
        },
      }}
    >
      <div className={styles.content}>
        <h1></h1>
      </div>
    </motion.div>

    <div className={styles.mainContentForm}>
      <div className={styles.introduction}>
        <h2>Politica de Privacidade</h2>
        <br />
        <span>Política Privacidade. 
            A sua privacidade é importante para nós. <br />
            É política do Buffet Cicareli respeitar a sua privacidade em relação 
            a qualquer informação sua que possamos coletar no site Buffet Cicareli, 
            e outros sites que possuímos e operamos. <br /> Solicitamos informações pessoais 
            apenas quando realmente precisamos delas para lhe fornecer um serviço. <br /> 
            Fazemo-lo por meios justos e legais, com o seu conhecimento e consentimento. <br /> 
            Também informamos por que estamos coletando e como será usado. <br /> 
            Apenas retemos as informações coletadas pelo tempo necessário 
            para fornecer o serviço solicitado. <br /> Quando armazenamos dados, 
            protegemos dentro de meios comercialmente aceitáveis 
            para evitar perdas e roubos, bem como acesso, divulgação, 
            cópia, uso ou modificação não autorizados. <br /> Não compartilhamos informações de identificação 
            pessoal publicamente ou com terceiros, exceto quando exigido por lei. <br /> 
            O nosso site pode ter links para sites externos que não são operados por nós. <br /> 
            Esteja ciente de que não temos controle sobre o conteúdo e práticas desses sites 
            e não podemos aceitar responsabilidade por suas respectivas 
            políticas de privacidade. <br />Você é livre para recusar a nossa solicitação de informações pessoais, 
            entendendo que talvez não possamos fornecer alguns dos serviços desejados. <br /> O uso continuado 
            de nosso site será considerado como aceitação de nossas práticas em torno de privacidade 
            e informações pessoais. <br /> Se você tiver alguma dúvida sobre como lidamos com dados do usuário
            e informações pessoais, entre em contacto conosco. <br /> <br />
            Compromisso do Usuário <br /> <br />
            
            O usuário se compromete a fazer uso adequado dos conteúdos e da informação que o 
            Buffet Cicareli oferece no site e com caráter enunciativo, 
            mas não limitativo: <br /> <br />
            A) Não se envolver em atividades que sejam ilegais ou contrárias à boa fé a à ordem pública;<br /><br />
            B) Não difundir propaganda ou conteúdo de natureza racista, xenofóbica, bet365 brasil ou azar,
            qualquer tipo de pornografia ilegal, de apologia ao terrorismo ou contra os direitos humanos;<br /><br />
            C) Não causar danos aos sistemas físicos (hardwares) e lógicos (softwares) do Buffet Cicareli, 
            de seus fornecedores ou terceiros, para introduzir ou disseminar vírus informáticos ou quaisquer 
            outros sistemas de hardware ou software que sejam capazes de causar danos anteriormente mencionados. <br />
            <br />
            Esta política é efetiva a partir de 17 de Janeiro de 2023 às 20:27
        </span>
      </div>
    </div>
    <FooterCompleto />
  </div></div>
  )
}
