on:
  push:
    branches: 
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3
      - name: Add NPM
        uses: actions/setup-node@v1
          with:
            node-version: 12
          - run: npm install --frozen-lockfile
          - run: npm run build
          - run: npm run export
      - name: 📂 Sync files
          uses: SamKirkland/FTP-Deploy-Action@4.3.3
            with:
              server: ${{ secrets.ftp_host }}
              username: ${{ secrets.ftp_user }}
              password: ${{ secrets.ftp_password }}
              local-dir: './out'
              server-dir: 'public_html/'